### ISSUE TITLE
Faveo App Issues List

### ISSUE THREAD

**Issue by sujit223** [ladybirdweb/faveo-helpdesk-android-app#8]
In Inbox tickets when tickets get loaded starting tickets doesn't take gravator as an profile pic.

While refreshing the tickets, tickets no. do get fetch by pagination but when we refreshed every time due to which the paginated next results display on top and can't find a way to fetch recent tickets.

Ticket owner name is not displaying on the inbox page.

Subject should be bold or in larger font as per UI. Also when go inside the ticket detail page,Subject it is reflecting not available but in Inbox page it is reflecting the subject.

Ticket Conversation page the system replier name is not displaying.And it should be a internal note.
Conversation gravator is not displaying.

Ticket Status is not chooseable. Department is taking ID and it is also not choosable.

Name is displaying ID,it should display name. Email is not available. Source is displaying as ID. It should display as source list select> web> email > agent panel.

Last Message is displaying as null.

Assigned to names are hardcoded. 

In conversation all the messages are repeating on refresh.

Client replies are coming as HTML messages.

Navignation Menu is not displayed on the ticket detail page

In conversation list the ticket replier names are not displayed as support, client and nothing for internal notes.

cc is not working.

In my tickets list always we get something went wrong! status.

Name is not displaying in client list and make name in Bold form.Gravator is not dispalyed for profile pic. While going to profile page of a client it always display something went wrong!
Organization name in user profile is hard coded.

Account status Active is hard coded and doesn't include in HTML Prototype.User name is not displayed and profile pic is not coming as gravator.
Open Ticket and closed ticket doesn't fetch the information and something went wrong! message is displaying.

For Create Ticket:

Email is displaying as invalid.
Phone no. should not be required field.
Help Topics seems to be hard corded.
Assign to Agents seems to be hard coded
Message displays on submit "invalid assign"
Ticket doesn't created from mobile. 

@sumitl920 @bhanu2217 @ssmittal @karthikladybird

**Comment by sumitl920** [comment]
1.
In Inbox tickets when tickets get loaded starting tickets doesn't take gravator as an profile pic.

⚫Fixed

---

2.
While refreshing the tickets, tickets no. do get fetch by pagination but when we refreshed every time due to which the paginated next results display on top and can't find a way to fetch recent tickets.

⚫Fixed

---

3.
Ticket owner name is not displaying on the inbox page.

⚫Fixed

---

4.
Subject should be bold or in larger font as per UI. Also when go inside the ticket detail page,Subject it is reflecting not available but in Inbox page it is reflecting the subject.

⚫Fixed

---

6.
⚫On token expiry, I get null because headers are not set. Works fine with postman
read more at
http://stackoverflow.com/questions/17121213/java-io-ioexception-no-authentication-challenges-found
and please fix this

---

7.
Ticket Conversation page the system replier name is not displaying. And it should be a internal note.
Conversation gravator is not displaying.
In conversation list the ticket replier names are not displayed as support, client and nothing for internal notes.

⚫Fixed

---

8.
In conversation all the messages are repeating on refresh.
⚫Fixed

---

9.
Client replies are coming as HTML messages.
⚫Fixed

---

10.
Navignation Menu is not displayed on the ticket detail page
⚫Will not be fixed
This change, though looks straight forward, requires lot of structural changes and is time consuming.
How I have designed navigation: Objects which are accessible from menu, will show menu because they are on the same screen. I just swap contents in and out of same screen.
Ticket Detail and Client Detail are two different screens apart from above, and hence cannot share same navigation.

---

11.
In my tickets list always we get something went wrong! status.

⚫Fixed

---

12.
Name is not displaying in client list and make name in Bold form.
Gravator is not dispalyed for profile pic.
While going to profile page of a client it always display something went wrong!
Organization name in user profile is hard coded.
Account status Active is hard coded and doesn't include in HTML Prototype.
User name is not displayed and profile pic is not coming as gravator.

⚫Fixed

---

13.
Open Ticket and closed ticket doesn't fetch the information and something went wrong! message is displaying.

⚫ Fixed

---

14.
Ticket Status is not chooseable. 
Department is taking ID and it is also not choosable.
Name is displaying ID, it should display name. 
Email is not available. 
Source is displaying as ID. It should display as source list select> web> email > agent panel.
Last Message is displaying as null.
Assigned to names are hardcoded. 
cc is not working.

⚫ Fixed

---

15.
For Create Ticket:
Email is displaying as invalid.
Phone no. should not be required field.
Help Topics seems to be hard corded.
Assign to Agents seems to be hard coded
Message displays on submit "invalid assign"
Ticket doesn't created from mobile.
cc is not working.

⚫ Fixed

---

**Comment by bhanu2217** [comment]
@vijaysebastian Can you please check and respond

**Comment by vijaysebastian** [comment]
> In my tickets list always we get something went wrong! status.
> 
> ⚫I hit this url with user id and api key:
> http://ladybirdweb.com/support/api/v1/helpdesk/my-tickets
> 
> Postman says:
> 
> 404 Not Found.

I have changed the url for get my ticket, please check the api doc. Api Number 28 and 29

**Comment by bhanu2217** [comment]
@vijaysebastian Please try and provide fix to all API issues today
@sujit223 See if something is related to your code also

**Comment by vijaysebastian** [comment]
> ⚫Picture value is not correct. See what you send in any one of ticketList.
> ⚫Send me Organization name and Account status Active along with above data.

I have changed

**Comment by vijaysebastian** [comment]
> ⚫Response I receive:
> {"result":
> [
> {
> "id":"5781",
> "pid":"0",
> "ticket_id":"1562",
> "staff_id":"0",
> "user_id":"243",
> "poster":"client",
> "source":null,
> "title":"Changes to Web Page \"Types of yoga",
> "body":"Some big HTML code",
> "is_internal":"0",
> "format":"",
> "ip_address":"",
> "created_at":"2016-04-15 07:15:20",
> "updated_at":"2016-04-15 07:15:36"
> }
> ]
> }
> There is no name, no gravator

I have changed response in api/v1/helpdesk/ticket-thread please look

**Comment by vijaysebastian** [comment]
Please use faveohelpdesk.com/demo for testing. I didn't update on ladybirdweb.com/support

**Comment by vijaysebastian** [comment]
> ⚫On token expiry, I get null because headers are not set. Works fine with postman
> read more at
> http://stackoverflow.com/questions/17121213/java-io-ioexception-no-authentication-challenges-found
> and please fix this

Please clarify me, why you are searching values in header?, now directly you will get the response from body

**Comment by sumitl920** [comment]
I do not search for headers here. Android connection API searchs for those in the response. It does not give me any response back(it gives me null) if it does not find headers.

**Comment by vijaysebastian** [comment]
@sumitl920 as we discussed I am passing  `Authenticate →xBasic realm: fake` in header for token related errors.

I have created new api to call all dependencies in one shot url is api/v1/helpdesk/dependency. 

Rest of everything I have fixed.
